version: '2'

services:
    db:
        image: mysql:5.6
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d
    app:
        image: php:5.6-apache
        restart: always
        ports:
            - '8000:80'
        volumes:
            - ./html:/var/www/html
        depends_on:
            - db
